server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://db:5432/kotlinbase
    username: postgres
    password: postgres

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: base
#       This property implies a new transaction and DB connection per each lazy load after a call to a JPARepository
#        Consider using eager loading when needed to avoid n+1 problem
        enable_lazy_load_no_trans: true

    hibernate:
      ddl-auto: none

baseproject:
  jwtSecret: TheDefinitiveSecret
#  jwtExpirationMs: 300000
#  jwtRefreshExpirationMs: 1800000
#  sessionDurationMs: 36000000
  jwtExpirationMs: 5000
  jwtRefreshExpirationMs: 15000
  sessionDurationMs: 40000
  jwtIssuerName: kotlinBaseIssuer
